default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: absurd_learning_app_development

test:
  <<: *default
  database: absurd_learning_app_test

production:
  adapter: postgresql
  encoding: unicode
  database: absurd_learning_app_production
  username: postgres
  password: postgres
  host: localhost
  port: 5432