default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    database: absurd_learning_app_development

  cable:
    <<: *default
    database: absurd_learning_app_development # Use the same database for Action Cable

  queue:
    <<: *default
    database: absurd_learning_app_development # Use the same database for SolidQueue

  cache:
    <<: *default
    database: absurd_learning_app_development # Use the same database for caching

test:
  primary:
    <<: *default
    database: absurd_learning_app_development # Use the development database for testing

  cable:
    <<: *default
    database: absurd_learning_app_development # Use the same database for Action Cable

  queue:
    <<: *default
    database: absurd_learning_app_development # Use the same database for SolidQueue

  cache:
    <<: *default
    database: absurd_learning_app_development # Use the same database for caching

production:
  primary:
    <<: *default
    database: absurd_learning_app_production
    username: postgres
    password: postgres
    host: localhost
    port: 5432

  cable:
    <<: *default
    database: absurd_learning_app_production # Use the same database for Action Cable
    username: postgres
    password: postgres
    host: localhost
    port: 5432

  queue:
    <<: *default
    database: absurd_learning_app_production # Use the same database for SolidQueue
    username: postgres
    password: postgres
    host: localhost
    port: 5432

  cache:
    <<: *default
    database: absurd_learning_app_production # Use the same database for caching
    username: postgres
    password: postgres
    host: localhost
    port: 5432