default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: absurd_learning_app_development

test:
  <<: *default
  database: absurd_learning_app_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>

  # 👇 Add this block to fix the cable error
  cable:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
