default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    database: absurd_learning_app_development

  cable:
    <<: *default
    database: absurd_learning_app_cable_development

  queue:
    <<: *default
    database: absurd_learning_app_queue_development

test:
  primary:
    <<: *default
    database: absurd_learning_app_test

  cable:
    <<: *default
    database: absurd_learning_app_cable_test

  queue:
    <<: *default
    database: absurd_learning_app_queue_test

production:
  primary:
    adapter: postgresql
    encoding: unicode
    database: absurd_learning_app_production
    username: postgres
    password: postgres
    host: localhost
    port: 5432

  cable:
    adapter: postgresql
    encoding: unicode
    database: absurd_learning_app_cable_production
    username: postgres
    password: postgres
    host: localhost
    port: 5432

  queue:
    adapter: postgresql
    encoding: unicode
    database: absurd_learning_app_queue_production
    username: postgres
    password: postgres
    host: localhost
    port: 5432